### ISSUE TITLE
babel-cli fails to find locally installed presets

### ISSUE THREAD

**Issue by Feuermurmel** [rt2zz/redux-persist-immutable#24]
I'm trying to run `babel` on a JSX file outside the project root (this happens in unit test when using a temporary directory under `/private/tmp`). It seems that babel fails to find presets installed into the same `node_modules` directory as `babel-cli`:

```
michi ~/Documents$ mkdir babel-preset-issue
michi ~/Documents$ cd babel-preset-issue/
michi ~/Documents/babel-preset-issue$ npm install babel-cli babel-preset-es2015
[...]
michi ~/Documents/babel-preset-issue$ echo 'a = 123;' > ../foo.jsx
michi ~/Documents/babel-preset-issue$ node_modules/.bin/babel --presets=es2015 ../foo.jsx
Error: Couldn't find preset "es2015" relative to directory ".."
    at /Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:216:65)
    at new File (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/file/index.js:139:24)
    at Pipeline.transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transform (/Users/michi/Documents/babel-preset-issue/node_modules/babel-cli/lib/babel/util.js:50:22)
```

**Comment by Feuermurmel** [comment]
I'm sorry for creating this issue, I messed up which tab I was working in.
